- name: Create hubot group
  group: name="{{hubot.group}}" state=present

- name: Create hubot user
  user: name="{{hubot.user}}" group="{{hubot.group}}"

- name: Checkout hubot repository
  git: repo="{{hubot.git}}" dest=/opt/hubot clone=yes update=yes
  notify: Restart Hubot server

- name: 'Set file permissions on hubot'
  file: path=/opt/hubot owner="{{hubot.user}}" group="{{hubot.group}}" state=touch state=directory mode=0755

- name: Install Systemd
  apt:
    pkg="systemd"
    state=present

- name: Install hubot
  shell: sudo -iu {{ hubot.user }} npm install /opt/hubot
  notify: Restart Hubot server

- name: Create inventory directory
  file: path=/opt/hubot/inventory state=directory owner="{{hubot.user}}" group="{{hubot.group}}" mode=0755

- name: Configure inventory/ec2.ini
  copy: src=inventory/ec2.ini dest=/opt/hubot/inventory/ec2.ini owner="{{hubot.user}}" group="{{hubot.group}}" mode=655

- name: Configure inventory/ec2.py
  copy: src=inventory/ec2.py dest=/opt/hubot/inventory/ec2.py owner="{{hubot.user}}" group="{{hubot.group}}" mode=755

- name: Configure PEM file
  copy: src="{{lookup('env','HUBOT_PEM_PATH')}}" dest="{{ lookup('env','HUBOT_ANSIBLE_PRIVATE_KEY') }}" owner="{{hubot.user}}" group="{{hubot.group}}"

- name: Protect PEM file
  shell: bash -lc "chmod 400 {{ lookup('env','HUBOT_ANSIBLE_PRIVATE_KEY') }}"

- name: Configure hubot service
  template: src=hubot.service.j2 dest=/etc/systemd/system/hubot.service owner=root group=root mode=0744
  notify:
    - Reload Hubot daemon
    - Restart Hubot server

- name: Enable hubot service at boot
  service: name=hubot enabled=yes
