- name: Install GoCD APT repository
  lineinfile: dest=/etc/apt/sources.list.d/gocd.list regexp=^deb line="deb http://dl.bintray.com/gocd/gocd-deb/ /" create=yes state=present

- name: Install GoCD APT key
  apt_key: url=https://bintray.com/user/downloadSubjectPublicKey?username=gocd state=present

- name: Update APT
  apt: update_cache=yes

- name: Install zip utils
  apt:
    pkg="{{item}}"
    state=present
  with_items:
    - zip
    - unzip

- name: Install bzip2
  apt:
    pkg=bzip2
    state=present

- name: Install build-essential
  apt:
    pkg=build-essential
    state=present

- name: Install libfontconfig1
  apt:
    pkg=libfontconfig1
    state=present

- name: Install Git
  apt:
    pkg=git
    state=present

# http://stackoverflow.com/questions/32707201/selenium-standalone-server-not-starting
- name: Fix Selenium issue
  shell: rm /dev/random; mknod /dev/random c 1 9

- name: Install GoCD agent
  apt:
    pkg="go-agent"
    state=present

- name: Create ~/.ssh directory
  file: path=/var/go/.ssh state=directory owner=go group=go mode=0700

- name: Delete known_hosts
  file: path=~/.ssh/known_hosts state=absent
  sudo: yes
  sudo_user: go

- name: Configure Github as a known host
  lineinfile:
    dest: ~/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"
  become: yes
  become_user: go

- name: Configure nodes as a known host
  shell: ssh-keyscan -t rsa {{item}} >> ~/.ssh/known_hosts
  become: yes
  become_user: go
  with_items:
    - "{{node_dev_server.ec2_private_ip_address}}"
    - "{{node_demo_server.ec2_private_ip_address}}"

- name: Configure Agent SSH private key
  copy:
    src=goagent_rsa
    dest=~/.ssh/goagent_rsa
    owner=go
    group=go
    mode=0400
  become: yes
  become_user: go

- name: Configure agent guid
  copy: content={{hostvars[inventory_hostname].ec2_id}} dest=/var/lib/go-agent/config/guid.txt
  notify: Restart GoCD agent

- name: Configure agent auto registration key
  lineinfile: dest=/var/lib/go-agent/config/autoregister.properties regexp=^agent.auto.register.key= line="agent.auto.register.key=123456789abcdef" create=yes state=present
  notify: Restart GoCD agent

- name: Configure agent hostname
  lineinfile: dest=/var/lib/go-agent/config/autoregister.properties regexp=^agent.auto.register.hostname= line="agent.auto.register.hostname={{inventory_hostname}}" create=yes state=present
  notify: Restart GoCD agent

- name: Configure GO_SERVER environment variable
  lineinfile: dest=/etc/default/go-agent regexp=^GO_SERVER= line="GO_SERVER={{gocd_server.ec2_private_ip_address}}" state=present
  notify: Restart GoCD agent

- name: Configure AGENT_MAX_MEM environment variable
  lineinfile: dest=/etc/default/go-agent regexp="^export AGENT_MAX_MEM=" line="export AGENT_MAX_MEM={{gocd_max_mem}}" state=present
  notify: Restart GoCD agent

- name: Configure GitHub OAuth Token
  template: src=dotgithub.j2 dest=~/.github owner=go group=go mode=0644
  become: yes
  become_user: go
  notify: Restart GoCD server

- name: Enable go-agent service at boot
  service: name=go-agent enabled=yes
