- hosts: "{{lookup('env','CLIENT')}}_{{lookup('env','ENV')}}_node_dev"
  user: admin
  sudo: yes

  roles:
    - common
    - nvm
    - nginx
    - node

- hosts: "{{lookup('env','CLIENT')}}_{{lookup('env','ENV')}}_node_demo"
  user: admin
  sudo: yes

  roles:
    - common
    - nvm
    - nginx
    - node
